
disabled_rules: # rule identifiers to exclude from running
 # - trailing_newline
    # - opening_brace
    # - empty_count
    # - comma
    # - colon
    # - force_cast
     - type_name
    # - variable_name_min_length
    # - trailing_semicolon
    # - force_try
    # - function_body_length
    # - nesting
     - variable_name
    # - conditional_binding_cascade
    # - variable_name_max_length
    # - operator_whitespace
    # - control_statement
    # - legacy_constant
    # - line_length
    # - return_arrow_whitespace
    - trailing_whitespace
    # - closing_brace
    # - statement_position
    # - type_body_length
    # - todo
    # - legacy_constructor
    # - valid_docs
    # - missing_docs
    # - file_length
    # - leading_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods



# configurable rules can be customized from this configuration file

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 150

# # naming rules can set warnings/errors for min_length and max_length
# # additionally they can set excluded names
# type_name:
#   min_length: 4 # only warning
#   max_length: # warning and error
#     warning: 40
#     error: 50
#   excluded: iPhone # excluded via string
# identifier_name:
#   min_length: # only min_length
#     error: 4 # only error
#   excluded: # excluded via string array
#     - id
#     - URL
#     - GlobalAPIKey
# reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)


type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
cyclomatic_complexity: 
  warning: 2
  error: 12
variable_name:
  max_length:
    warning: 15
error: 20